//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 数据库课程设计作业.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Act
    {
        public System.DateTime adate { get; set; }
        public string lname { get; set; }
        public string tname { get; set; }
        public string ldriver { get; set; }
    
        public virtual Locomotive Locomotive { get; set; }
        public virtual Train Train { get; set; }
    }
}
