//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 数据库课程设计作业.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locomotive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locomotive()
        {
            this.Act = new HashSet<Act>();
        }
    
        public string lname { get; set; }
        public string lmanufacturer { get; set; }
        public Nullable<System.DateTime> lbirth { get; set; }
        public string ljv { get; set; }
        public string lduan { get; set; }
        public byte[] lphoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Act> Act { get; set; }
    }
}
