//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 数据库课程设计作业.domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Locomotive_systemEntities : DbContext
    {
        public Locomotive_systemEntities()
            : base("name=Locomotive_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Act> Act { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<Locomotive> Locomotive { get; set; }
        public virtual DbSet<Orderdetail> Orderdetail { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Seat> Seat { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<Train> Train { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Yunzhuan> Yunzhuan { get; set; }
        public virtual DbSet<Chepiao> Chepiao { get; set; }
        public virtual DbSet<Liechegaikuang> Liechegaikuang { get; set; }
        public virtual DbSet<Liecheshikebiao> Liecheshikebiao { get; set; }
        public virtual DbSet<Availableseats> Availableseats { get; set; }
    }
}
