//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 数据库课程设计作业.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public Nullable<int> oid { get; set; }
        public int odid { get; set; }
        public Nullable<int> seid { get; set; }
        public Nullable<System.DateTime> takedate { get; set; }
        public string takername { get; set; }
        public string takestart { get; set; }
        public string takeend { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
    }
}
